python run_viper.py --env-name Frozenlake4x4 --output-dir out_size --max-leaf-nodes 2 --seed 4
python run_viper.py --env-name Frozenlake4x4 --output-dir out_size --max-leaf-nodes 2 --seed 5
python run_viper.py --env-name Frozenlake4x4 --output-dir out_size --max-leaf-nodes 2 --seed 6
python run_viper.py --env-name Frozenlake4x4 --output-dir out_size --max-leaf-nodes 4 --seed 4
python run_viper.py --env-name Frozenlake4x4 --output-dir out_size --max-leaf-nodes 4 --seed 5
python run_viper.py --env-name Frozenlake4x4 --output-dir out_size --max-leaf-nodes 4 --seed 6
python run_viper.py --env-name Frozenlake4x4 --output-dir out_size --max-leaf-nodes 8 --seed 4
python run_viper.py --env-name Frozenlake4x4 --output-dir out_size --max-leaf-nodes 8 --seed 5
python run_viper.py --env-name Frozenlake4x4 --output-dir out_size --max-leaf-nodes 8 --seed 6
python run_viper.py --env-name Frozenlake4x4 --output-dir out_size --max-leaf-nodes 16 --seed 4
python run_viper.py --env-name Frozenlake4x4 --output-dir out_size --max-leaf-nodes 16 --seed 5
python run_viper.py --env-name Frozenlake4x4 --output-dir out_size --max-leaf-nodes 16 --seed 6
python run_viper.py --env-name Frozenlake4x4 --output-dir out_size --max-leaf-nodes 32 --seed 4
python run_viper.py --env-name Frozenlake4x4 --output-dir out_size --max-leaf-nodes 32 --seed 5
python run_viper.py --env-name Frozenlake4x4 --output-dir out_size --max-leaf-nodes 32 --seed 6
python run_viper.py --env-name Frozenlake4x4 --output-dir out_size --max-leaf-nodes 64 --seed 4
python run_viper.py --env-name Frozenlake4x4 --output-dir out_size --max-leaf-nodes 64 --seed 5
python run_viper.py --env-name Frozenlake4x4 --output-dir out_size --max-leaf-nodes 64 --seed 6
python run_viper.py --env-name Frozenlake4x4 --output-dir out_size --max-leaf-nodes 128 --seed 4
python run_viper.py --env-name Frozenlake4x4 --output-dir out_size --max-leaf-nodes 128 --seed 5
python run_viper.py --env-name Frozenlake4x4 --output-dir out_size --max-leaf-nodes 128 --seed 6
python run_viper.py --env-name CartPole-v1 --output-dir out_size --max-leaf-nodes 2 --seed 4
python run_viper.py --env-name CartPole-v1 --output-dir out_size --max-leaf-nodes 2 --seed 5
python run_viper.py --env-name CartPole-v1 --output-dir out_size --max-leaf-nodes 2 --seed 6
python run_viper.py --env-name CartPole-v1 --output-dir out_size --max-leaf-nodes 4 --seed 4
python run_viper.py --env-name CartPole-v1 --output-dir out_size --max-leaf-nodes 4 --seed 5
python run_viper.py --env-name CartPole-v1 --output-dir out_size --max-leaf-nodes 4 --seed 6
python run_viper.py --env-name CartPole-v1 --output-dir out_size --max-leaf-nodes 8 --seed 4
python run_viper.py --env-name CartPole-v1 --output-dir out_size --max-leaf-nodes 8 --seed 5
python run_viper.py --env-name CartPole-v1 --output-dir out_size --max-leaf-nodes 8 --seed 6
python run_viper.py --env-name CartPole-v1 --output-dir out_size --max-leaf-nodes 16 --seed 4
python run_viper.py --env-name CartPole-v1 --output-dir out_size --max-leaf-nodes 16 --seed 5
python run_viper.py --env-name CartPole-v1 --output-dir out_size --max-leaf-nodes 16 --seed 6
python run_viper.py --env-name CartPole-v1 --output-dir out_size --max-leaf-nodes 32 --seed 4
python run_viper.py --env-name CartPole-v1 --output-dir out_size --max-leaf-nodes 32 --seed 5
python run_viper.py --env-name CartPole-v1 --output-dir out_size --max-leaf-nodes 32 --seed 6
python run_viper.py --env-name CartPole-v1 --output-dir out_size --max-leaf-nodes 64 --seed 4
python run_viper.py --env-name CartPole-v1 --output-dir out_size --max-leaf-nodes 64 --seed 5
python run_viper.py --env-name CartPole-v1 --output-dir out_size --max-leaf-nodes 64 --seed 6
python run_viper.py --env-name CartPole-v1 --output-dir out_size --max-leaf-nodes 128 --seed 4
python run_viper.py --env-name CartPole-v1 --output-dir out_size --max-leaf-nodes 128 --seed 5
python run_viper.py --env-name CartPole-v1 --output-dir out_size --max-leaf-nodes 128 --seed 6
python run_viper.py --env-name PendulumBangBang --output-dir out_size --max-leaf-nodes 2 --seed 4
python run_viper.py --env-name PendulumBangBang --output-dir out_size --max-leaf-nodes 2 --seed 5
python run_viper.py --env-name PendulumBangBang --output-dir out_size --max-leaf-nodes 2 --seed 6
python run_viper.py --env-name PendulumBangBang --output-dir out_size --max-leaf-nodes 4 --seed 4
python run_viper.py --env-name PendulumBangBang --output-dir out_size --max-leaf-nodes 4 --seed 5
python run_viper.py --env-name PendulumBangBang --output-dir out_size --max-leaf-nodes 4 --seed 6
python run_viper.py --env-name PendulumBangBang --output-dir out_size --max-leaf-nodes 8 --seed 4
python run_viper.py --env-name PendulumBangBang --output-dir out_size --max-leaf-nodes 8 --seed 5
python run_viper.py --env-name PendulumBangBang --output-dir out_size --max-leaf-nodes 8 --seed 6
python run_viper.py --env-name PendulumBangBang --output-dir out_size --max-leaf-nodes 16 --seed 4
python run_viper.py --env-name PendulumBangBang --output-dir out_size --max-leaf-nodes 16 --seed 5
python run_viper.py --env-name PendulumBangBang --output-dir out_size --max-leaf-nodes 16 --seed 6
python run_viper.py --env-name PendulumBangBang --output-dir out_size --max-leaf-nodes 32 --seed 4
python run_viper.py --env-name PendulumBangBang --output-dir out_size --max-leaf-nodes 32 --seed 5
python run_viper.py --env-name PendulumBangBang --output-dir out_size --max-leaf-nodes 32 --seed 6
python run_viper.py --env-name PendulumBangBang --output-dir out_size --max-leaf-nodes 64 --seed 4
python run_viper.py --env-name PendulumBangBang --output-dir out_size --max-leaf-nodes 64 --seed 5
python run_viper.py --env-name PendulumBangBang --output-dir out_size --max-leaf-nodes 64 --seed 6
python run_viper.py --env-name PendulumBangBang --output-dir out_size --max-leaf-nodes 128 --seed 4
python run_viper.py --env-name PendulumBangBang --output-dir out_size --max-leaf-nodes 128 --seed 5
python run_viper.py --env-name PendulumBangBang --output-dir out_size --max-leaf-nodes 128 --seed 6
python run_viper.py --env-name CartPoleSwingup --output-dir out_size --max-leaf-nodes 2 --seed 4
python run_viper.py --env-name CartPoleSwingup --output-dir out_size --max-leaf-nodes 2 --seed 5
python run_viper.py --env-name CartPoleSwingup --output-dir out_size --max-leaf-nodes 2 --seed 6
python run_viper.py --env-name CartPoleSwingup --output-dir out_size --max-leaf-nodes 4 --seed 4
python run_viper.py --env-name CartPoleSwingup --output-dir out_size --max-leaf-nodes 4 --seed 5
python run_viper.py --env-name CartPoleSwingup --output-dir out_size --max-leaf-nodes 4 --seed 6
python run_viper.py --env-name CartPoleSwingup --output-dir out_size --max-leaf-nodes 8 --seed 4
python run_viper.py --env-name CartPoleSwingup --output-dir out_size --max-leaf-nodes 8 --seed 5
python run_viper.py --env-name CartPoleSwingup --output-dir out_size --max-leaf-nodes 8 --seed 6
python run_viper.py --env-name CartPoleSwingup --output-dir out_size --max-leaf-nodes 16 --seed 4
python run_viper.py --env-name CartPoleSwingup --output-dir out_size --max-leaf-nodes 16 --seed 5
python run_viper.py --env-name CartPoleSwingup --output-dir out_size --max-leaf-nodes 16 --seed 6
python run_viper.py --env-name CartPoleSwingup --output-dir out_size --max-leaf-nodes 32 --seed 4
python run_viper.py --env-name CartPoleSwingup --output-dir out_size --max-leaf-nodes 32 --seed 5
python run_viper.py --env-name CartPoleSwingup --output-dir out_size --max-leaf-nodes 32 --seed 6
python run_viper.py --env-name CartPoleSwingup --output-dir out_size --max-leaf-nodes 64 --seed 4
python run_viper.py --env-name CartPoleSwingup --output-dir out_size --max-leaf-nodes 64 --seed 5
python run_viper.py --env-name CartPoleSwingup --output-dir out_size --max-leaf-nodes 64 --seed 6
python run_viper.py --env-name CartPoleSwingup --output-dir out_size --max-leaf-nodes 128 --seed 4
python run_viper.py --env-name CartPoleSwingup --output-dir out_size --max-leaf-nodes 128 --seed 5
python run_viper.py --env-name CartPoleSwingup --output-dir out_size --max-leaf-nodes 128 --seed 6
