python run_dtpo.py --env-name Acrobot-v1 --output-dir out --seed 1
python run_dtpo.py --env-name CartPole-v1 --output-dir out --seed 1
python run_dtpo.py --env-name CartPoleSwingup --output-dir out --seed 1
python run_dtpo.py --env-name PendulumBangBang --output-dir out --seed 1
python run_dtpo.py --env-name Navigation3D --output-dir out --seed 1
python run_dtpo.py --env-name Blackjack --output-dir out --seed 1
python run_dtpo.py --env-name Frozenlake4x4 --output-dir out --seed 1
python run_dtpo.py --env-name Frozenlake8x8 --output-dir out --seed 1
python run_dtpo.py --env-name Frozenlake12x12 --output-dir out --seed 1
python run_dtpo.py --env-name InventoryManagement --output-dir out --seed 1
python run_dtpo.py --env-name SystemAdministrator1 --output-dir out --seed 1
python run_dtpo.py --env-name SystemAdministrator2 --output-dir out --seed 1
python run_dtpo.py --env-name SystemAdministratorTree --output-dir out --seed 1
python run_dtpo.py --env-name TictactoeVsRandom --output-dir out --seed 1
python run_dtpo.py --env-name TigerVsAntelope --output-dir out --seed 1
python run_dtpo.py --env-name TrafficIntersection --output-dir out --seed 1
python run_dtpo.py --env-name Xor --output-dir out --seed 1
python run_dtpo.py --env-name Acrobot-v1 --output-dir out --seed 2
python run_dtpo.py --env-name CartPole-v1 --output-dir out --seed 2
python run_dtpo.py --env-name CartPoleSwingup --output-dir out --seed 2
python run_dtpo.py --env-name PendulumBangBang --output-dir out --seed 2
python run_dtpo.py --env-name Navigation3D --output-dir out --seed 2
python run_dtpo.py --env-name Blackjack --output-dir out --seed 2
python run_dtpo.py --env-name Frozenlake4x4 --output-dir out --seed 2
python run_dtpo.py --env-name Frozenlake8x8 --output-dir out --seed 2
python run_dtpo.py --env-name Frozenlake12x12 --output-dir out --seed 2
python run_dtpo.py --env-name InventoryManagement --output-dir out --seed 2
python run_dtpo.py --env-name SystemAdministrator1 --output-dir out --seed 2
python run_dtpo.py --env-name SystemAdministrator2 --output-dir out --seed 2
python run_dtpo.py --env-name SystemAdministratorTree --output-dir out --seed 2
python run_dtpo.py --env-name TictactoeVsRandom --output-dir out --seed 2
python run_dtpo.py --env-name TigerVsAntelope --output-dir out --seed 2
python run_dtpo.py --env-name TrafficIntersection --output-dir out --seed 2
python run_dtpo.py --env-name Xor --output-dir out --seed 2
python run_dtpo.py --env-name Acrobot-v1 --output-dir out --seed 3
python run_dtpo.py --env-name CartPole-v1 --output-dir out --seed 3
python run_dtpo.py --env-name CartPoleSwingup --output-dir out --seed 3
python run_dtpo.py --env-name PendulumBangBang --output-dir out --seed 3
python run_dtpo.py --env-name Navigation3D --output-dir out --seed 3
python run_dtpo.py --env-name Blackjack --output-dir out --seed 3
python run_dtpo.py --env-name Frozenlake4x4 --output-dir out --seed 3
python run_dtpo.py --env-name Frozenlake8x8 --output-dir out --seed 3
python run_dtpo.py --env-name Frozenlake12x12 --output-dir out --seed 3
python run_dtpo.py --env-name InventoryManagement --output-dir out --seed 3
python run_dtpo.py --env-name SystemAdministrator1 --output-dir out --seed 3
python run_dtpo.py --env-name SystemAdministrator2 --output-dir out --seed 3
python run_dtpo.py --env-name SystemAdministratorTree --output-dir out --seed 3
python run_dtpo.py --env-name TictactoeVsRandom --output-dir out --seed 3
python run_dtpo.py --env-name TigerVsAntelope --output-dir out --seed 3
python run_dtpo.py --env-name TrafficIntersection --output-dir out --seed 3
python run_dtpo.py --env-name Xor --output-dir out --seed 3
python run_viper.py --env-name Acrobot-v1 --output-dir out --seed 1
python run_viper.py --env-name CartPole-v1 --output-dir out --seed 1
python run_viper.py --env-name CartPoleSwingup --output-dir out --seed 1
python run_viper.py --env-name PendulumBangBang --output-dir out --seed 1
python run_viper.py --env-name Navigation3D --output-dir out --seed 1
python run_viper.py --env-name Blackjack --output-dir out --seed 1
python run_viper.py --env-name Frozenlake4x4 --output-dir out --seed 1
python run_viper.py --env-name Frozenlake8x8 --output-dir out --seed 1
python run_viper.py --env-name Frozenlake12x12 --output-dir out --seed 1
python run_viper.py --env-name InventoryManagement --output-dir out --seed 1
python run_viper.py --env-name SystemAdministrator1 --output-dir out --seed 1
python run_viper.py --env-name SystemAdministrator2 --output-dir out --seed 1
python run_viper.py --env-name SystemAdministratorTree --output-dir out --seed 1
python run_viper.py --env-name TictactoeVsRandom --output-dir out --seed 1
python run_viper.py --env-name TigerVsAntelope --output-dir out --seed 1
python run_viper.py --env-name TrafficIntersection --output-dir out --seed 1
python run_viper.py --env-name Xor --output-dir out --seed 1
python run_viper.py --env-name Acrobot-v1 --output-dir out --seed 2
python run_viper.py --env-name CartPole-v1 --output-dir out --seed 2
python run_viper.py --env-name CartPoleSwingup --output-dir out --seed 2
python run_viper.py --env-name PendulumBangBang --output-dir out --seed 2
python run_viper.py --env-name Navigation3D --output-dir out --seed 2
python run_viper.py --env-name Blackjack --output-dir out --seed 2
python run_viper.py --env-name Frozenlake4x4 --output-dir out --seed 2
python run_viper.py --env-name Frozenlake8x8 --output-dir out --seed 2
python run_viper.py --env-name Frozenlake12x12 --output-dir out --seed 2
python run_viper.py --env-name InventoryManagement --output-dir out --seed 2
python run_viper.py --env-name SystemAdministrator1 --output-dir out --seed 2
python run_viper.py --env-name SystemAdministrator2 --output-dir out --seed 2
python run_viper.py --env-name SystemAdministratorTree --output-dir out --seed 2
python run_viper.py --env-name TictactoeVsRandom --output-dir out --seed 2
python run_viper.py --env-name TigerVsAntelope --output-dir out --seed 2
python run_viper.py --env-name TrafficIntersection --output-dir out --seed 2
python run_viper.py --env-name Xor --output-dir out --seed 2
python run_viper.py --env-name Acrobot-v1 --output-dir out --seed 3
python run_viper.py --env-name CartPole-v1 --output-dir out --seed 3
python run_viper.py --env-name CartPoleSwingup --output-dir out --seed 3
python run_viper.py --env-name PendulumBangBang --output-dir out --seed 3
python run_viper.py --env-name Navigation3D --output-dir out --seed 3
python run_viper.py --env-name Blackjack --output-dir out --seed 3
python run_viper.py --env-name Frozenlake4x4 --output-dir out --seed 3
python run_viper.py --env-name Frozenlake8x8 --output-dir out --seed 3
python run_viper.py --env-name Frozenlake12x12 --output-dir out --seed 3
python run_viper.py --env-name InventoryManagement --output-dir out --seed 3
python run_viper.py --env-name SystemAdministrator1 --output-dir out --seed 3
python run_viper.py --env-name SystemAdministrator2 --output-dir out --seed 3
python run_viper.py --env-name SystemAdministratorTree --output-dir out --seed 3
python run_viper.py --env-name TictactoeVsRandom --output-dir out --seed 3
python run_viper.py --env-name TigerVsAntelope --output-dir out --seed 3
python run_viper.py --env-name TrafficIntersection --output-dir out --seed 3
python run_viper.py --env-name Xor --output-dir out --seed 3
python run_ppo.py --env-name Acrobot-v1 --output-dir out --seed 1
python run_ppo.py --env-name CartPole-v1 --output-dir out --seed 1
python run_ppo.py --env-name CartPoleSwingup --output-dir out --seed 1
python run_ppo.py --env-name PendulumBangBang --output-dir out --seed 1
python run_ppo.py --env-name Navigation3D --output-dir out --seed 1
python run_ppo.py --env-name Blackjack --output-dir out --seed 1
python run_ppo.py --env-name Frozenlake4x4 --output-dir out --seed 1
python run_ppo.py --env-name Frozenlake8x8 --output-dir out --seed 1
python run_ppo.py --env-name Frozenlake12x12 --output-dir out --seed 1
python run_ppo.py --env-name InventoryManagement --output-dir out --seed 1
python run_ppo.py --env-name SystemAdministrator1 --output-dir out --seed 1
python run_ppo.py --env-name SystemAdministrator2 --output-dir out --seed 1
python run_ppo.py --env-name SystemAdministratorTree --output-dir out --seed 1
python run_ppo.py --env-name TictactoeVsRandom --output-dir out --seed 1
python run_ppo.py --env-name TigerVsAntelope --output-dir out --seed 1
python run_ppo.py --env-name TrafficIntersection --output-dir out --seed 1
python run_ppo.py --env-name Xor --output-dir out --seed 1
python run_ppo.py --env-name Acrobot-v1 --output-dir out --seed 2
python run_ppo.py --env-name CartPole-v1 --output-dir out --seed 2
python run_ppo.py --env-name CartPoleSwingup --output-dir out --seed 2
python run_ppo.py --env-name PendulumBangBang --output-dir out --seed 2
python run_ppo.py --env-name Navigation3D --output-dir out --seed 2
python run_ppo.py --env-name Blackjack --output-dir out --seed 2
python run_ppo.py --env-name Frozenlake4x4 --output-dir out --seed 2
python run_ppo.py --env-name Frozenlake8x8 --output-dir out --seed 2
python run_ppo.py --env-name Frozenlake12x12 --output-dir out --seed 2
python run_ppo.py --env-name InventoryManagement --output-dir out --seed 2
python run_ppo.py --env-name SystemAdministrator1 --output-dir out --seed 2
python run_ppo.py --env-name SystemAdministrator2 --output-dir out --seed 2
python run_ppo.py --env-name SystemAdministratorTree --output-dir out --seed 2
python run_ppo.py --env-name TictactoeVsRandom --output-dir out --seed 2
python run_ppo.py --env-name TigerVsAntelope --output-dir out --seed 2
python run_ppo.py --env-name TrafficIntersection --output-dir out --seed 2
python run_ppo.py --env-name Xor --output-dir out --seed 2
python run_ppo.py --env-name Acrobot-v1 --output-dir out --seed 3
python run_ppo.py --env-name CartPole-v1 --output-dir out --seed 3
python run_ppo.py --env-name CartPoleSwingup --output-dir out --seed 3
python run_ppo.py --env-name PendulumBangBang --output-dir out --seed 3
python run_ppo.py --env-name Navigation3D --output-dir out --seed 3
python run_ppo.py --env-name Blackjack --output-dir out --seed 3
python run_ppo.py --env-name Frozenlake4x4 --output-dir out --seed 3
python run_ppo.py --env-name Frozenlake8x8 --output-dir out --seed 3
python run_ppo.py --env-name Frozenlake12x12 --output-dir out --seed 3
python run_ppo.py --env-name InventoryManagement --output-dir out --seed 3
python run_ppo.py --env-name SystemAdministrator1 --output-dir out --seed 3
python run_ppo.py --env-name SystemAdministrator2 --output-dir out --seed 3
python run_ppo.py --env-name SystemAdministratorTree --output-dir out --seed 3
python run_ppo.py --env-name TictactoeVsRandom --output-dir out --seed 3
python run_ppo.py --env-name TigerVsAntelope --output-dir out --seed 3
python run_ppo.py --env-name TrafficIntersection --output-dir out --seed 3
python run_ppo.py --env-name Xor --output-dir out --seed 3
